# Generated by Django 4.2.20 on 2026-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PremiumRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "property_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contacted",
                    models.BooleanField(
                        default=False,
                        help_text="Tick this once you've reached out to the requester.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (won't be sent to the user).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium request",
                "verbose_name_plural": "Premium requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
