# Generated by Django 4.2.20 on 2026-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "property_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The property page the request was sent from (blank if from the home page).",
                        max_length=500,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("property", "Property page"), ("home", "Home page")],
                        default="property",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contacted",
                    models.BooleanField(
                        default=False,
                        help_text="Tick this once you've reached out to the requester.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (won't be sent to the user).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest request",
                "verbose_name_plural": "Interest requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
