# Generated by Django 4.2.20 on 2026-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_interestrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestrequest",
            name="budget",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="regions",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="timeline",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="visited_japan",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
