# Generated by Django 4.2.20 on 2026-08-15 17:44
#
# Replaces the `contacted` boolean with a proper lead lifecycle. The operation
# order is deliberate and MUST NOT be re-generated by makemigrations: the new
# columns are added first, `contacted` is copied into `status`, and only then
# is the old column dropped. The auto-generated order put RemoveField first,
# which would have destroyed the data before it could be carried over.

from django.db import migrations, models


def carry_contacted_into_status(apps, schema_editor):
    """contacted=True was the only progress signal that existed, so it maps to
    'consultation done' — the furthest point we can honestly claim."""
    InterestRequest = apps.get_model("membership", "InterestRequest")
    InterestRequest.objects.filter(contacted=True).update(status="call_done")


def restore_contacted_from_status(apps, schema_editor):
    """Reverse: anything past 'new' counts as having been contacted."""
    InterestRequest = apps.get_model("membership", "InterestRequest")
    InterestRequest.objects.exclude(status="new").update(contacted=True)


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_interestrequest_budget_interestrequest_regions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestrequest",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically when status becomes Purchase closed or Dead.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_response", "Went quiet on us"),
                    ("price", "Price / total cost"),
                    ("financing", "Couldn't finance it"),
                    ("cold_feet", "Cold feet — decided not to buy"),
                    ("agent_silent", "Agent never worked the lead"),
                    ("property_gone", "Property was already sold/delisted"),
                    ("not_serious", "Never a serious buyer"),
                    ("other", "Other (see notes)"),
                ],
                default="",
                help_text="Only meaningful when status is Dead. Fill this in every time — it's the only way to learn why the funnel leaks.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="referred_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically when status first reaches 'Referred to agent'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="referred_to",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which licensed agent this lead was handed to.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "1. New — not yet worked"),
                    ("call_booked", "2. Consultation booked"),
                    ("call_done", "3. Consultation done"),
                    ("referred", "4. Referred to agent"),
                    ("viewing", "5. Viewing arranged"),
                    ("offer", "6. Offer made"),
                    ("won", "7. Purchase closed"),
                    ("lost", "✕ Dead"),
                ],
                db_index=True,
                default="new",
                help_text="Where this lead currently sits in the funnel.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interestrequest",
            name="status_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically whenever status changes — drives the 'stale' warning in the list view.",
                null=True,
            ),
        ),
        # Carry the old signal over BEFORE the column disappears.
        migrations.RunPython(
            carry_contacted_into_status,
            restore_contacted_from_status,
        ),
        migrations.RemoveField(
            model_name="interestrequest",
            name="contacted",
        ),
    ]
