# Generated by Django 4.2.20 on 2026-08-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0014_geocodedplace"),
        ("membership", "0004_remove_interestrequest_contacted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Price bucket key, e.g. 'u50' (see front.views.PRICE_BUCKETS).",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user wants alerts for new matches. Nothing sends these yet — the flag records intent so we know if it's worth building.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved search",
                "verbose_name_plural": "Saved searches",
                "ordering": ["-created_at"],
                "unique_together": {("user", "city", "price")},
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="inventory.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved property",
                "verbose_name_plural": "Saved properties",
                "ordering": ["-created_at"],
                "unique_together": {("user", "property")},
            },
        ),
    ]
