# Generated by Django 4.2.20 on 2026-08-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_geocodedplace"),
        ("membership", "0006_subscription_propertyview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_index=True, help_text="Start of the call, in UTC."
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "visitor_timezone",
                    models.CharField(
                        blank=True,
                        help_text="IANA zone the visitor booked from, e.g. Europe/Madrid.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hold", "Awaiting payment"),
                            ("paid", "Paid — booked"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Call completed"),
                        ],
                        db_index=True,
                        default="hold",
                        max_length=12,
                    ),
                ),
                (
                    "hold_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When an unpaid hold stops blocking the slot.",
                        null=True,
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("paypal_capture_id", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="The listing that prompted the call, when there was one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="inventory.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "ordering": ["starts_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="consultation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("hold", "paid", "completed"))),
                fields=("starts_at",),
                name="one_live_consultation_per_slot",
            ),
        ),
    ]
