# Generated by Django 4.2.20 on 2026-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0007_consultation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="PayPal's subscription id (I-XXXX). Empty until they approve.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
