# Generated by Django 4.2.20 on 2026-08-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_geocodedplace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0008_alter_subscription_paypal_subscription_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("listing_url", models.URLField(blank=True, max_length=500)),
                ("listing_location", models.CharField(blank=True, max_length=255)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="What the requester told us."
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Your notes. Never shown to the requester.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New — needs a reply"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("booked", "Inspection booked"),
                            ("unavailable", "Couldn't arrange access"),
                            ("declined", "They decided against it"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What you quoted them, once you know.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="The property they want inspected.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_requests",
                        to="inventory.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the requester was signed in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection request",
                "verbose_name_plural": "Inspection requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
