# Generated by Django 4.2.20 on 2026-08-20 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0009_inspectionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("checkout", "Opened PayPal checkout"),
                            ("waitlist", "Asked for Pro while it wasn't on sale"),
                        ],
                        db_index=True,
                        default="checkout",
                        max_length=20,
                    ),
                ),
                (
                    "billing_configured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Pro could actually be bought at the time. False means they wanted it and the site had nothing to sell them.",
                    ),
                ),
                (
                    "from_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The page they came from — usually the listing whose locked fields sent them to /pro/.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when they were signed in. Goes null if the account is deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pro_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pro attempt",
                "verbose_name_plural": "Pro attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
