# Generated by Django 4.2.20 on 2026-08-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_property_energy_performance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0010_proattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeskReportOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "listing_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "listing_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Anything the buyer asked us to look at specifically.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("paid", "Paid — report owed"),
                            ("delivered", "Report sent"),
                            ("cancelled", "Cancelled at PayPal"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("paypal_capture_id", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=8)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Your notes. Never shown to the buyer.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="The listing the report is about.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desk_report_orders",
                        to="inventory.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the buyer was signed in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desk_report_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Desk report order",
                "verbose_name_plural": "Desk report orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
