"""Desk reports stop being a purchase and become a Pro entitlement.

Hand-written rather than autogenerated so the table is *renamed*, not dropped and
recreated. Nothing could plausibly have ordered one — the flow was live for
minutes and nothing linked to it — but "probably empty" is not a reason to write
a migration that would lose a paying customer's order if it were wrong.

The PayPal columns go with it: there is no payment in this model any more, and a
column that can only ever hold a stale value is worse than no column.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_deskreportorder"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeskReportOrder",
            new_name="DeskReportRequest",
        ),
        migrations.AlterModelOptions(
            name="deskreportrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Desk report request",
                "verbose_name_plural": "Desk report requests",
            },
        ),
        migrations.RemoveField(model_name="deskreportrequest", name="paypal_order_id"),
        migrations.RemoveField(model_name="deskreportrequest", name="paypal_capture_id"),
        migrations.RemoveField(model_name="deskreportrequest", name="amount"),
        migrations.RemoveField(model_name="deskreportrequest", name="currency"),
        migrations.RemoveField(model_name="deskreportrequest", name="paid_at"),
        migrations.AlterField(
            model_name="deskreportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested — not started"),
                    ("in_progress", "In progress"),
                    ("delivered", "Report sent"),
                    ("declined", "Declined — allowance returned"),
                ],
                db_index=True,
                default="requested",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="deskreportrequest",
            name="buyer_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Anything the member asked us to look at specifically.",
            ),
        ),
        migrations.AlterField(
            model_name="deskreportrequest",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Your notes. Never shown to the member.",
            ),
        ),
        migrations.AlterField(
            model_name="deskreportrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The Pro member who claimed it. Null only if the "
                "account was deleted afterwards.",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="desk_report_requests",
                to="auth.user",
            ),
        ),
        migrations.AlterField(
            model_name="deskreportrequest",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                help_text="The listing the report is about.",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="desk_report_requests",
                to="inventory.property",
            ),
        ),
    ]
