# Generated by Django 4.2.20 on 2025-03-31 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=254,
                        null=True,
                        upload_to="property_images/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("floor_plan", models.CharField(max_length=255)),
                ("building_area", models.FloatField()),
                ("land_area", models.FloatField()),
                ("parking", models.CharField(max_length=255)),
                ("construction", models.CharField(max_length=255)),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="inventory.propertyimage",
                    ),
                ),
            ],
        ),
    ]
