# Generated by Django 4.2.20 on 2025-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="building_area",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="property", name="price", field=models.CharField(max_length=255),
        ),
    ]
