# Generated by Django 4.2.20 on 2025-04-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_property_images_propertyimage_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="show_in_front",
            field=models.BooleanField(default=True),
        ),
    ]
