# Generated by Django 4.2.20 on 2025-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_property_show_in_front"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="building_coverage_ratio",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="building_structure",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="city_planning",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="construction_date",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="current_status",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="property",
            name="equipment",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="floor_area_ratio",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="handover",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="land_category",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="land_rights",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="road_condition",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="setback",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="traffic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="transaction_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="url",
            field=models.URLField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="zoning",
            field=models.CharField(default="", max_length=255),
        ),
    ]
