# Generated by Django 4.2.20 on 2025-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_propertyimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_plan",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="property", name="price", field=models.IntegerField(default=0),
        ),
    ]
