# Generated by Django 4.2.20 on 2025-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_property_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="building_area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="building_coverage_ratio",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="building_structure",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="city_planning",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="construction",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="current_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="property",
            name="equipment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_area_ratio",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="handover",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_category",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="parking",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="road_condition",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="setback",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="traffic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="transaction_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="zoning",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
