# Generated by Django 4.2.20 on 2026-06-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_property_created_at_property_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
