# Generated by Django 4.2.20 on 2026-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_property_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Normalised 'City, Prefecture' string, e.g. 'Kitami City, Hokkaido'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the geocoder matched — useful for spotting bad matches.",
                        max_length=500,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Lookup attempts so far; lets the command skip hopeless keys.",
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Geocoded place",
                "verbose_name_plural": "Geocoded places",
                "ordering": ["key"],
            },
        ),
    ]
