# Generated by Django 4.2.20 on 2026-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_geocodedplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="nearest_station",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nearest station named in `traffic`, without the word Station.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="needs_bus",
            field=models.BooleanField(
                default=False,
                help_text="The transit description involves a bus, i.e. no walkable rail.",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="station_distance_km",
            field=models.FloatField(
                blank=True,
                help_text="Used when the listing gives a distance instead of a walk time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="station_walk_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Minutes on foot from nearest_station. NULL means the listing names no walkable station — usually because access is by bus.",
                null=True,
            ),
        ),
    ]
