# Generated by Django 4.2.20 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_property_nearest_station_property_needs_bus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="energy_performance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="エネルギー消費性能 — energy rating.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="estimated_utility_cost",
            field=models.CharField(
                blank=True,
                default="",
                help_text="目安光熱費 — the listing's own estimate of monthly running cost.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="insulation_performance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="断熱性能 — insulation grade. Decides whether a rural house is habitable in winter.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listed_on",
            field=models.DateField(
                blank=True,
                help_text="情報提供日 — when the listing was published. The real days-on-market clock; created_at only records when we first saw it.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="renovation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="リフォーム — what has been renovated and when.",
                max_length=500,
            ),
        ),
    ]
