# Generated by Django 4.2.20 on 2026-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_property_energy_performance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="label",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="What the source called this photo — SUUMO's alt text, e.g. 病院 (hospital), 公園 (park), 担当者 (the agent). Blank for the property's own photos, and for everything scraped before this field existed.",
                max_length=64,
            ),
        ),
    ]
