# Generated by Django 4.2.20 on 2025-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("property_url", models.URLField(blank=True, max_length=255)),
                (
                    "social_media",
                    models.CharField(
                        choices=[("facebook", "Facebook"), ("instagram", "Instagram")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
