# Generated by Django 4.2.20 on 2025-06-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="content_type",
            field=models.CharField(
                choices=[("post", "Post"), ("reel", "Reel")],
                default="post",
                max_length=50,
            ),
        ),
    ]
