# Generated by Django 4.2.20 on 2025-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_socialpost_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="sound_track",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
