# Generated by Django 4.2.20 on 2025-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_socialpost_sound_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="ai_caption",
            field=models.TextField(blank=True, default=""),
        ),
    ]
