# Generated by Django 4.2.20 on 2025-07-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_socialpost_ai_caption"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.IntegerField()),
                ("comment_id", models.IntegerField(unique=True)),
                ("comment", models.CharField(max_length=200)),
                ("replied", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
