# Generated by Django 4.2.20 on 2025-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_socialcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcomment",
            name="self_comment",
            field=models.BooleanField(default=False),
        ),
    ]
