# Generated by Django 4.2.20 on 2026-08-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_socialcomment_self_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="avg_watch_time_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Average watch time in milliseconds (reels only). The number that decides how far a reel travels.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="caption_angle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Creative direction the caption was written to.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="comments_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="insights_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="likes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="media_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Instagram/Facebook id of the published media. Blank means we cannot fetch insights for this one.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="overlay_hook",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The phrase burnt into the video, when there was one.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="reach",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="saves",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="shares",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="total_interactions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="views",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
