# Generated by Django 4.2.20 on 2026-08-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_socialpost_avg_watch_time_ms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("listing", "Listing"),
                            ("faq", "FAQ"),
                            ("news", "News"),
                            ("data", "Data / stats"),
                            ("guide", "Guide"),
                        ],
                        db_index=True,
                        default="faq",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "1. Draft — needs review"),
                            ("approved", "2. Approved — will post"),
                            ("rejected", "✕ Rejected"),
                            ("posted", "3. Posted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank", "Curated question bank"),
                            ("comment", "Asked by a follower"),
                        ],
                        default="bank",
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=120)),
                ("question", models.CharField(max_length=500)),
                (
                    "answer",
                    models.TextField(
                        help_text="The answer as it appears on the card. Edit it here before approving; the card is re-rendered on approval."
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Caption as it will be posted.",
                    ),
                ),
                (
                    "card_paths",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Newline-separated local paths of the rendered cards, in carousel order.",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="This answer states something specific enough to be wrong. Check it before approving.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="socialcomment",
            name="question",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The follower's comment we were replying to. Blank on rows written before this field existed.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="post_kind",
            field=models.CharField(
                choices=[
                    ("listing", "Listing"),
                    ("faq", "FAQ"),
                    ("news", "News"),
                    ("data", "Data / stats"),
                    ("guide", "Guide"),
                ],
                db_index=True,
                default="listing",
                help_text="Editorial format. Everything posted before this field existed was a listing, which is why that is the default.",
                max_length=32,
            ),
        ),
    ]
