# Generated by Django 4.2.20 on 2026-08-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_contentdraft_socialcomment_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="content_type",
            field=models.CharField(
                choices=[("post", "Post"), ("reel", "Reel"), ("story", "Story")],
                default="post",
                max_length=50,
            ),
        ),
    ]
