# Generated by Django 4.2.20 on 2026-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0009_alter_socialpost_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="social_media",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                ],
                max_length=50,
            ),
        ),
    ]
