# Generated by Django 4.2.20 on 2025-04-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_property_building_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="inventory.propertyimage",
            ),
        ),
    ]
