# Generated by Django 4.2.20 on 2025-04-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_property_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="images",),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.property",
            ),
        ),
    ]
