# Generated by Django 4.2.20 on 2025-04-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_propertyimage_show_in_front"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="show_in_front",
            field=models.BooleanField(default=True),
        ),
    ]
