# Generated by Django 4.2.20 on 2025-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="first_image",
            field=models.BooleanField(default=False),
        ),
    ]
